#!/usr/bin/env bash
#
# One-command end-to-end demo on a local Hardhat node.
# Spins up: Hardhat node -> deploy contract -> data provider -> consumer agent.
# No testnet ETH, no faucet, no manual setup. ~30 seconds.
#
set -euo pipefail

HARDHAT_PORT=8545
SERVER_PORT=4021
RPC_URL="http://127.0.0.1:$HARDHAT_PORT"
SERVER_URL="http://localhost:$SERVER_PORT"

HARDHAT_LOG="/tmp/agentic-payment-hardhat.log"
SERVER_LOG="/tmp/agentic-payment-server.log"

# Hardhat dev mnemonic accounts (publicly known, only for local testing)
DEPLOYER_PK="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
PROVIDER_PK="0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"
PROVIDER_ADDR="0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
AGENT_PK="0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a"

HARDHAT_PID=""
SERVER_PID=""
ENV_BACKED_UP=false

cleanup() {
  echo ""
  echo "[demo] Cleaning up..."
  if [[ -n "$SERVER_PID" ]]; then kill "$SERVER_PID" 2>/dev/null || true; fi
  if [[ -n "$HARDHAT_PID" ]]; then kill "$HARDHAT_PID" 2>/dev/null || true; fi
  if [[ "$ENV_BACKED_UP" == "true" ]] && [[ -f .env.demo-backup ]]; then
    mv .env.demo-backup .env
    echo "[demo] Restored your original .env"
  fi
  echo "[demo] Done."
}
trap cleanup EXIT INT TERM

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  AGENTIC PAYMENT SYSTEM -- LOCAL E2E DEMO                  ║"
echo "║  Local Hardhat blockchain, no testnet ETH needed           ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

if ! command -v lsof >/dev/null 2>&1; then
  echo "[demo] WARNING: lsof not found; cannot detect port conflicts" >&2
else
  for port in "$HARDHAT_PORT" "$SERVER_PORT"; do
    pids=$(lsof -ti ":$port" 2>/dev/null || true)
    if [[ -n "$pids" ]]; then
      echo "[demo] Port $port busy (pid $pids), killing..."
      echo "$pids" | xargs kill -9 2>/dev/null || true
      sleep 1
    fi
  done
fi

if [[ -f .env ]]; then
  cp .env .env.demo-backup
  ENV_BACKED_UP=true
  echo "[demo] Backed up existing .env"
fi

cat > .env <<EOF
# Auto-generated by scripts/demo-local.sh -- restored after run
RPC_URL=$RPC_URL
SERVER_URL=$SERVER_URL
PORT=$SERVER_PORT
ENABLE_X402=true
DEPLOYER_PRIVATE_KEY=$DEPLOYER_PK
PROVIDER_WALLET_ADDRESS=$PROVIDER_ADDR
PROVIDER_PRIVATE_KEY=$PROVIDER_PK
PROVIDER_RECORDER_ADDRESS=$PROVIDER_ADDR
AGENT_PRIVATE_KEY=$AGENT_PK
DATA_MARKETPLACE_ADDRESS=
QUERY_INTERVAL_SECONDS=1
MAX_QUERIES=0
EOF
echo "[demo] Wrote .env for local Hardhat"

# 1. Start Hardhat node
echo ""
echo "[demo] [1/4] Starting Hardhat local node..."
npx hardhat node > "$HARDHAT_LOG" 2>&1 &
HARDHAT_PID=$!

ready=false
for _ in $(seq 1 40); do
  if curl -s -X POST -H "Content-Type: application/json" \
       --data '{"jsonrpc":"2.0","method":"net_version","id":1}' \
       "$RPC_URL" 2>/dev/null | grep -q '"result"'; then
    ready=true
    break
  fi
  sleep 0.5
done
if [[ "$ready" != "true" ]]; then
  echo "[demo] FAILED: Hardhat node did not start. See $HARDHAT_LOG"
  exit 1
fi
echo "[demo]       Hardhat node running at $RPC_URL"

# 2. Deploy contract
echo ""
echo "[demo] [2/4] Deploying DataMarketplace + registering datasets..."
DEPLOY_OUT=$(npx hardhat run scripts/deploy.cjs --network localhost 2>&1)
echo "$DEPLOY_OUT" | sed 's/^/         /'

ADDR=$(echo "$DEPLOY_OUT" | grep "^DATA_MARKETPLACE_ADDRESS=" | head -1 | cut -d= -f2 | tr -d '[:space:]')
if [[ -z "$ADDR" ]]; then
  echo "[demo] FAILED to capture contract address from deploy output"
  exit 1
fi

# macOS sed needs '' after -i, GNU sed doesn't; use a tempfile to stay portable
awk -v addr="$ADDR" '/^DATA_MARKETPLACE_ADDRESS=/{print "DATA_MARKETPLACE_ADDRESS=" addr; next} {print}' .env > .env.tmp
mv .env.tmp .env

# 3. Start data provider server
echo ""
echo "[demo] [3/4] Starting data provider server..."
npx tsx server/index.ts > "$SERVER_LOG" 2>&1 &
SERVER_PID=$!

ready=false
for _ in $(seq 1 30); do
  if curl -s "$SERVER_URL/health" 2>/dev/null | grep -q '"ok":true'; then
    ready=true
    break
  fi
  sleep 0.5
done
if [[ "$ready" != "true" ]]; then
  echo "[demo] FAILED: Server did not start. See $SERVER_LOG"
  exit 1
fi
echo "[demo]       Server running at $SERVER_URL"

# 4. Run agent
echo ""
echo "[demo] [4/4] Running consumer agent..."
echo "═══════════════════════════════════════════════════════════════"
echo ""
npx tsx agent/index.ts

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "[demo] Demo complete."
echo "[demo]   Contract address: $ADDR (local Hardhat only)"
echo "[demo]   Hardhat log:      $HARDHAT_LOG"
echo "[demo]   Server log:       $SERVER_LOG"
