export interface SentimentData {
  ticker: string;
  score: number;
  signal: string;
  confidence: number;
  sources: number;
  summary: string;
}

export interface FinancialData {
  topic: string;
  headline: string;
  summary: string;
  impact: string;
  relevance: number;
}

export interface WeatherData {
  city: string;
  temperature_c: number;
  humidity_pct: number;
  conditions: string;
  wind_kph: number;
  forecast: string;
}

export interface CollectedData {
  sentiment: Map<string, SentimentData>;
  financial: Map<string, FinancialData>;
  weather: Map<string, WeatherData>;
}

export function createEmptyCollection(): CollectedData {
  return {
    sentiment: new Map(),
    financial: new Map(),
    weather: new Map(),
  };
}

function sentimentToRecommendation(score: number): string {
  if (score > 0.3) return "BUY";
  if (score < -0.3) return "SELL";
  return "HOLD";
}

function formatBar(value: number, min: number, max: number, width: number): string {
  const normalized = Math.max(0, Math.min(1, (value - min) / (max - min)));
  const filled = Math.round(normalized * width);
  return "█".repeat(filled) + "░".repeat(width - filled);
}

export function printReport(data: CollectedData, totalSpent: number): void {
  console.log("\n");
  console.log("╔══════════════════════════════════════════════════════════════╗");
  console.log("║            INVESTMENT RESEARCH REPORT                       ║");
  console.log("║            Generated by Autonomous Agent                    ║");
  console.log("║            Data purchased via x402 protocol                 ║");
  console.log("╚══════════════════════════════════════════════════════════════╝");

  // --- Sentiment Rankings ---
  console.log("\n┌─────────────────────────────────────────────────────────────┐");
  console.log("│ MARKET SENTIMENT RANKINGS                                   │");
  console.log("├────────┬───────┬────────┬────────────────────────┬──────────┤");
  console.log("│ Ticker │ Score │ Signal │ Sentiment Bar          │ Rec.     │");
  console.log("├────────┼───────┼────────┼────────────────────────┼──────────┤");

  const sentimentEntries = [...data.sentiment.entries()]
    .sort((a, b) => b[1].score - a[1].score);

  for (const [ticker, s] of sentimentEntries) {
    const score = s.score.toFixed(2).padStart(6);
    const signal = s.signal.padEnd(6);
    const bar = formatBar(s.score, -1, 1, 20);
    const rec = sentimentToRecommendation(s.score).padEnd(8);
    console.log(`│ ${ticker.padEnd(6)} │ ${score} │ ${signal} │ ${bar}   │ ${rec} │`);
  }

  console.log("└────────┴───────┴────────┴────────────────────────┴──────────┘");

  // --- Financial Highlights ---
  if (data.financial.size > 0) {
    console.log("\n┌─────────────────────────────────────────────────────────────┐");
    console.log("│ FINANCIAL HIGHLIGHTS                                        │");
    console.log("└─────────────────────────────────────────────────────────────┘");

    for (const [, f] of data.financial) {
      const impactIcon =
        f.impact === "positive" ? "(+)" :
        f.impact === "negative" ? "(-)" : "(~)";
      console.log(`  ${impactIcon} ${f.headline}`);
      console.log(`      ${f.summary}`);
    }
  }

  // --- Market Conditions ---
  if (data.weather.size > 0) {
    console.log("\n┌─────────────────────────────────────────────────────────────┐");
    console.log("│ TRADING HUB CONDITIONS                                      │");
    console.log("└─────────────────────────────────────────────────────────────┘");

    for (const [city, w] of data.weather) {
      console.log(`  ${city}: ${w.temperature_c}°C, ${w.conditions}, wind ${w.wind_kph} kph`);
    }
  }

  // --- Recommendation Summary ---
  console.log("\n┌─────────────────────────────────────────────────────────────┐");
  console.log("│ RECOMMENDATION SUMMARY                                      │");
  console.log("└─────────────────────────────────────────────────────────────┘");

  const buys: string[] = [];
  const holds: string[] = [];
  const sells: string[] = [];

  for (const [ticker, s] of sentimentEntries) {
    const rec = sentimentToRecommendation(s.score);
    if (rec === "BUY") buys.push(ticker);
    else if (rec === "SELL") sells.push(ticker);
    else holds.push(ticker);
  }

  if (buys.length > 0)  console.log(`  BUY:  ${buys.join(", ")}`);
  if (holds.length > 0) console.log(`  HOLD: ${holds.join(", ")}`);
  if (sells.length > 0) console.log(`  SELL: ${sells.join(", ")}`);

  console.log(`\n  Data sources: ${data.sentiment.size} sentiment + ${data.financial.size} financial + ${data.weather.size} weather`);
  console.log(`  Total data cost: $${totalSpent.toFixed(4)} USDC (paid autonomously via x402)`);
  console.log("");
}
